/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: tahoma12.c                                            *
* Font:        Tahoma                                                *
* Height:      12                                                    *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fonttahoma12;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0020[ 12] = { /* code 0020, SPACE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0021[ 12] = { /* code 0021, EXCLAMATION MARK */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0022[ 12] = { /* code 0022, QUOTATION MARK */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0023[ 12] = { /* code 0023, NUMBER SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X_X____,
  XXXX____,
  X_X_____,
  XXXX____,
  X_X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0024[ 12] = { /* code 0024, DOLLAR SIGN */
  ________,
  ________,
  ________,
  ________,
  _X______,
  XXX_____,
  XX______,
  XXX_____,
  XXX_____,
  XXX_____,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0025[ 12] = { /* code 0025, PERCENT SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X___X__,
  X_X_X___,
  _X_X_X__,
  ___XX_X_,
  __X__X__,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0026[ 12] = { /* code 0026, AMPERSAND */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  __X_____,
  XXX_____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0027[ 12] = { /* code 0027, APOSTROPHE */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0028[ 12] = { /* code 0028, LEFT PARENTHESIS */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  X_______,
  X_______,
  X_______,
  X_______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0029[ 12] = { /* code 0029, RIGHT PARENTHESIS */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  _X______,
  _X______,
  _X______,
  _X______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_002A[ 12] = { /* code 002A, ASTERISK */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_002B[ 12] = { /* code 002B, PLUS SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  XXX_____,
  _X______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_002C[ 12] = { /* code 002C, COMMA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_002D[ 12] = { /* code 002D, HYPHEN-MINUS */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_002E[ 12] = { /* code 002E, FULL STOP */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_002F[ 12] = { /* code 002F, SOLIDUS */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  X_______,
  X_______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0030[ 12] = { /* code 0030, DIGIT ZERO */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0031[ 12] = { /* code 0031, DIGIT ONE */
  ________,
  ________,
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0032[ 12] = { /* code 0032, DIGIT TWO */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  XX______,
  _X______,
  X_______,
  XX______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0033[ 12] = { /* code 0033, DIGIT THREE */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  _X______,
  X_______,
  _X______,
  X_______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0034[ 12] = { /* code 0034, DIGIT FOUR */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  X_X_____,
  XXX_____,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0035[ 12] = { /* code 0035, DIGIT FIVE */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  X_______,
  X_______,
  _X______,
  X_______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0036[ 12] = { /* code 0036, DIGIT SIX */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  X_______,
  XX______,
  XX______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0037[ 12] = { /* code 0037, DIGIT SEVEN */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0038[ 12] = { /* code 0038, DIGIT EIGHT */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  X_______,
  XX______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0039[ 12] = { /* code 0039, DIGIT NINE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  _X______,
  X_______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_003A[ 12] = { /* code 003A, COLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_003B[ 12] = { /* code 003B, SEMICOLON */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  _X______,
  _X______,
  X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_003C[ 12] = { /* code 003C, LESS-THAN SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  X_______,
  _X______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_003D[ 12] = { /* code 003D, EQUALS SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  ________,
  XX______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_003E[ 12] = { /* code 003E, GREATER-THAN SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  _X______,
  X_______,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_003F[ 12] = { /* code 003F, QUESTION MARK */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  __X_____,
  __X_____,
  _X______,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0040[ 12] = { /* code 0040, COMMERCIAL AT */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX____,
  _X_XX___,
  X_XXX___,
  X_XXX___,
  X__X____,
  _X__X___,
  __XX____};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0041[ 12] = { /* code 0041, LATIN CAPITAL LETTER A */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  X_X_____,
  X_X_____,
  XXX_____,
  X_X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0042[ 12] = { /* code 0042, LATIN CAPITAL LETTER B */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  X__X____,
  XXX_____,
  X__X____,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0043[ 12] = { /* code 0043, LATIN CAPITAL LETTER C */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X__X____,
  X_______,
  X__X____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0044[ 12] = { /* code 0044, LATIN CAPITAL LETTER D */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  X_X_____,
  X_X_____,
  X_X_____,
  XX______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0045[ 12] = { /* code 0045, LATIN CAPITAL LETTER E */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  X_______,
  XXX_____,
  X_______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0046[ 12] = { /* code 0046, LATIN CAPITAL LETTER F */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  X_______,
  XXX_____,
  X_______,
  X_______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0047[ 12] = { /* code 0047, LATIN CAPITAL LETTER G */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X__X____,
  X_XX____,
  X__X____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0048[ 12] = { /* code 0048, LATIN CAPITAL LETTER H */
  ________,
  ________,
  ________,
  ________,
  ________,
  X__X____,
  X__X____,
  XXXX____,
  X__X____,
  X__X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0049[ 12] = { /* code 0049, LATIN CAPITAL LETTER I */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_004A[ 12] = { /* code 004A, LATIN CAPITAL LETTER J */
  ________,
  ________,
  ________,
  ________,
  ________,
  __X_____,
  __X_____,
  __X_____,
  X_X_____,
  XX______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_004B[ 12] = { /* code 004B, LATIN CAPITAL LETTER K */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  XX______,
  XX______,
  XX______,
  X_X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_004C[ 12] = { /* code 004C, LATIN CAPITAL LETTER L */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_004D[ 12] = { /* code 004D, LATIN CAPITAL LETTER M */
  ________,
  ________,
  ________,
  ________,
  ________,
  X___X___,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  X_X_X___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_004E[ 12] = { /* code 004E, LATIN CAPITAL LETTER N */
  ________,
  ________,
  ________,
  ________,
  ________,
  X__X____,
  XX_X____,
  XXXX____,
  X_XX____,
  X__X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_004F[ 12] = { /* code 004F, LATIN CAPITAL LETTER O */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X__X____,
  X__X____,
  X__X____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0050[ 12] = { /* code 0050, LATIN CAPITAL LETTER P */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  X_X_____,
  XX______,
  X_______,
  X_______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0051[ 12] = { /* code 0051, LATIN CAPITAL LETTER Q */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X__X____,
  X__X____,
  X__X____,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0052[ 12] = { /* code 0052, LATIN CAPITAL LETTER R */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  X_X_____,
  XX______,
  X_X_____,
  X_X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0053[ 12] = { /* code 0053, LATIN CAPITAL LETTER S */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  X__X____,
  _XX_____,
  X__X____,
  _XXX____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0054[ 12] = { /* code 0054, LATIN CAPITAL LETTER T */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0055[ 12] = { /* code 0055, LATIN CAPITAL LETTER U */
  ________,
  ________,
  ________,
  ________,
  ________,
  X__X____,
  X__X____,
  X__X____,
  X__X____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0056[ 12] = { /* code 0056, LATIN CAPITAL LETTER V */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  X_X_____,
  X_X_____,
  X_X_____,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0057[ 12] = { /* code 0057, LATIN CAPITAL LETTER W */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_X___,
  X___X___,
  X___X___,
  X___X___,
  _X_X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0058[ 12] = { /* code 0058, LATIN CAPITAL LETTER X */
  ________,
  ________,
  ________,
  ________,
  ________,
  X__X____,
  _XX_____,
  _X______,
  _XX_____,
  X__X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0059[ 12] = { /* code 0059, LATIN CAPITAL LETTER Y */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  _X_X____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_005A[ 12] = { /* code 005A, LATIN CAPITAL LETTER Z */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  __X_____,
  _X______,
  X_______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_005B[ 12] = { /* code 005B, LEFT SQUARE BRACKET */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  X_______,
  X_______,
  X_______,
  X_______,
  XX______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_005C[ 12] = { /* code 005C, REVERSE SOLIDUS */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  _X______,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_005D[ 12] = { /* code 005D, RIGHT SQUARE BRACKET */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________,
  ________,
  ________,
  ________,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_005E[ 12] = { /* code 005E, CIRCUMFLEX ACCENT */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  X_X_____,
  X_X_____,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_005F[ 12] = { /* code 005F, LOW LINE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0060[ 12] = { /* code 0060, GRAVE ACCENT */
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_______,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0061[ 12] = { /* code 0061, LATIN SMALL LETTER A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XXX_____,
  X_X_____,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0062[ 12] = { /* code 0062, LATIN SMALL LETTER B */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  XX______,
  X_X_____,
  X_X_____,
  XX______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0063[ 12] = { /* code 0063, LATIN SMALL LETTER C */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X_______,
  X_______,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0064[ 12] = { /* code 0064, LATIN SMALL LETTER D */
  ________,
  ________,
  ________,
  ________,
  ________,
  __X_____,
  _XX_____,
  X_X_____,
  X_X_____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0065[ 12] = { /* code 0065, LATIN SMALL LETTER E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  XXX_____,
  X_______,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0066[ 12] = { /* code 0066, LATIN SMALL LETTER F */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0067[ 12] = { /* code 0067, LATIN SMALL LETTER G */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X_X_____,
  X_X_____,
  _XX_____,
  XX______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0068[ 12] = { /* code 0068, LATIN SMALL LETTER H */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  XXX_____,
  X_X_____,
  X_X_____,
  X_X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0069[ 12] = { /* code 0069, LATIN SMALL LETTER I */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_006A[ 12] = { /* code 006A, LATIN SMALL LETTER J */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_006B[ 12] = { /* code 006B, LATIN SMALL LETTER K */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  XX______,
  XX______,
  XX______,
  XX______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_006C[ 12] = { /* code 006C, LATIN SMALL LETTER L */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_006D[ 12] = { /* code 006D, LATIN SMALL LETTER M */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_006E[ 12] = { /* code 006E, LATIN SMALL LETTER N */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  X_X_____,
  X_X_____,
  X_X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_006F[ 12] = { /* code 006F, LATIN SMALL LETTER O */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  X_X_____,
  X_X_____,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0070[ 12] = { /* code 0070, LATIN SMALL LETTER P */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  X_X_____,
  X_X_____,
  XX______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0071[ 12] = { /* code 0071, LATIN SMALL LETTER Q */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X_X_____,
  X_X_____,
  _XX_____,
  __X_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0072[ 12] = { /* code 0072, LATIN SMALL LETTER R */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  X_______,
  X_______,
  X_______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0073[ 12] = { /* code 0073, LATIN SMALL LETTER S */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  XXX_____,
  __X_____,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0074[ 12] = { /* code 0074, LATIN SMALL LETTER T */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  XX______,
  X_______,
  X_______,
  XX______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0075[ 12] = { /* code 0075, LATIN SMALL LETTER U */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  X_X_____,
  X_X_____,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0076[ 12] = { /* code 0076, LATIN SMALL LETTER V */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  X_X_____,
  X_X_____,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0077[ 12] = { /* code 0077, LATIN SMALL LETTER W */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  XXX_____,
  XXX_____,
  _X_X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0078[ 12] = { /* code 0078, LATIN SMALL LETTER X */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  _X______,
  _X______,
  X_X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0079[ 12] = { /* code 0079, LATIN SMALL LETTER Y */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  XX______,
  _X______,
  _X______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_007A[ 12] = { /* code 007A, LATIN SMALL LETTER Z */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  _X______,
  XX______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_007B[ 12] = { /* code 007B, LEFT CURLY BRACKET */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  X_______,
  _X______,
  _X______,
  _X______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_007C[ 12] = { /* code 007C, VERTICAL LINE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_007D[ 12] = { /* code 007D, RIGHT CURLY BRACKET */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  _X______,
  ________,
  _X______,
  _X______,
  XX______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_007E[ 12] = { /* code 007E, TILDE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  ________,
  ________,
  ________,
  ________};

/* Start of unicode area <Cyrillic> */
GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0410[ 12] = { /* code 0410, CYRILLIC CAPITAL LETTER A */
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  X_X_____,
  X_X_____,
  XXX_____,
  X_X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0411[ 12] = { /* code 0411, CYRILLIC CAPITAL LETTER BE */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  X_______,
  XX______,
  X_X_____,
  XX______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0412[ 12] = { /* code 0412, CYRILLIC CAPITAL LETTER VE */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  X__X____,
  XXX_____,
  X__X____,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0413[ 12] = { /* code 0413, CYRILLIC CAPITAL LETTER GHE */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  X_______,
  X_______,
  X_______,
  X_______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0414[ 12] = { /* code 0414, CYRILLIC CAPITAL LETTER DE */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  _XX_____,
  XXXX____,
  X__X____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0415[ 12] = { /* code 0415, CYRILLIC CAPITAL LETTER IE */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  X_______,
  XXX_____,
  X_______,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0416[ 12] = { /* code 0416, CYRILLIC CAPITAL LETTER ZHE */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  _XXX____,
  _XXX____,
  _XXX____,
  X_X_X___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0417[ 12] = { /* code 0417, CYRILLIC CAPITAL LETTER ZE */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  __X_____,
  _X______,
  __X_____,
  XX______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0418[ 12] = { /* code 0418, CYRILLIC CAPITAL LETTER I */
  ________,
  ________,
  ________,
  ________,
  ________,
  X__X____,
  X_XX____,
  XXXX____,
  XX_X____,
  X__X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0419[ 12] = { /* code 0419, CYRILLIC CAPITAL LETTER SHORT I */
  ________,
  ________,
  ________,
  _XX_____,
  ________,
  X__X____,
  X_XX____,
  XXXX____,
  XX_X____,
  X__X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_041A[ 12] = { /* code 041A, CYRILLIC CAPITAL LETTER KA */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  XX______,
  XX______,
  XX______,
  X_X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_041B[ 12] = { /* code 041B, CYRILLIC CAPITAL LETTER EL */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  X_X_____,
  X_X_____,
  X_X_____,
  X_X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_041C[ 12] = { /* code 041C, CYRILLIC CAPITAL LETTER EM */
  ________,
  ________,
  ________,
  ________,
  ________,
  X___X___,
  XX_XX___,
  XX_XX___,
  XX_XX___,
  X_X_X___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_041D[ 12] = { /* code 041D, CYRILLIC CAPITAL LETTER EN */
  ________,
  ________,
  ________,
  ________,
  ________,
  X__X____,
  X__X____,
  XXXX____,
  X__X____,
  X__X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_041E[ 12] = { /* code 041E, CYRILLIC CAPITAL LETTER O */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X__X____,
  X__X____,
  X__X____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_041F[ 12] = { /* code 041F, CYRILLIC CAPITAL LETTER PE */
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  X__X____,
  X__X____,
  X__X____,
  X__X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0420[ 12] = { /* code 0420, CYRILLIC CAPITAL LETTER ER */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  X_X_____,
  XX______,
  X_______,
  X_______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0421[ 12] = { /* code 0421, CYRILLIC CAPITAL LETTER ES */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X__X____,
  X_______,
  X__X____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0422[ 12] = { /* code 0422, CYRILLIC CAPITAL LETTER TE */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XXX____,
  __X_____,
  __X_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0423[ 12] = { /* code 0423, CYRILLIC CAPITAL LETTER U */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  X_X_____,
  X_X_____,
  _X______,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0424[ 12] = { /* code 0424, CYRILLIC CAPITAL LETTER EF */
  ________,
  ________,
  ________,
  ________,
  ________,
  __X_____,
  XXXX____,
  X_X_____,
  XXXX____,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0425[ 12] = { /* code 0425, CYRILLIC CAPITAL LETTER HA */
  ________,
  ________,
  ________,
  ________,
  ________,
  X__X____,
  _XX_____,
  _X______,
  _XX_____,
  X__X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0426[ 12] = { /* code 0426, CYRILLIC CAPITAL LETTER TSE */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  X_X_____,
  X_X_____,
  X_X_____,
  XXXX____,
  ___X____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0427[ 12] = { /* code 0427, CYRILLIC CAPITAL LETTER CHE */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  X_X_____,
  XXX_____,
  __X_____,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0428[ 12] = { /* code 0428, CYRILLIC CAPITAL LETTER SHA */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0429[ 12] = { /* code 0429, CYRILLIC CAPITAL LETTER SHCHA */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  XXXXXX__,
  _____X__,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_042A[ 12] = { /* code 042A, CYRILLIC CAPITAL LETTER HARD SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _XX_____,
  _X_X____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_042B[ 12] = { /* code 042B, CYRILLIC CAPITAL LETTER YERU */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_______,
  XX______,
  X_X_____,
  XX______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_042C[ 12] = { /* code 042C, CYRILLIC CAPITAL LETTER SOFT SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_______,
  XX______,
  X_X_____,
  XX______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_042D[ 12] = { /* code 042D, CYRILLIC CAPITAL LETTER E */
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  X_X_____,
  _XX_____,
  X_X_____,
  XX______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_042E[ 12] = { /* code 042E, CYRILLIC CAPITAL LETTER YU */
  ________,
  ________,
  ________,
  ________,
  ________,
  X__X____,
  X_X_X___,
  XXX_X___,
  X_X_X___,
  X__X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_042F[ 12] = { /* code 042F, CYRILLIC CAPITAL LETTER YA */
  ________,
  ________,
  ________,
  ________,
  ________,
  __XX____,
  _X_X____,
  __XX____,
  _X_X____,
  _X_X____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0430[ 12] = { /* code 0430, CYRILLIC SMALL LETTER A */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XXX_____,
  X_X_____,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0431[ 12] = { /* code 0431, CYRILLIC SMALL LETTER BE */
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  XX______,
  X_X_____,
  X_X_____,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0432[ 12] = { /* code 0432, CYRILLIC SMALL LETTER VE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  XX______,
  X_X_____,
  XX______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0433[ 12] = { /* code 0433, CYRILLIC SMALL LETTER GHE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  X_______,
  X_______,
  X_______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0434[ 12] = { /* code 0434, CYRILLIC SMALL LETTER DE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  _X______,
  XX______,
  XXX_____,
  X_X_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0435[ 12] = { /* code 0435, CYRILLIC SMALL LETTER IE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  XXX_____,
  X_______,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0436[ 12] = { /* code 0436, CYRILLIC SMALL LETTER ZHE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXX____,
  _XXX____,
  _XXX____,
  X_X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0437[ 12] = { /* code 0437, CYRILLIC SMALL LETTER ZE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  X_______,
  _X______,
  XX______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0438[ 12] = { /* code 0438, CYRILLIC SMALL LETTER I */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  XXX_____,
  XXX_____,
  X_X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0439[ 12] = { /* code 0439, CYRILLIC SMALL LETTER SHORT I */
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  ________,
  X_X_____,
  XXX_____,
  XXX_____,
  X_X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_043A[ 12] = { /* code 043A, CYRILLIC SMALL LETTER KA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  X_X_____,
  XX______,
  X_X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_043B[ 12] = { /* code 043B, CYRILLIC SMALL LETTER EL */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  _XX_____,
  _XX_____,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_043C[ 12] = { /* code 043C, CYRILLIC SMALL LETTER EM */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_043D[ 12] = { /* code 043D, CYRILLIC SMALL LETTER EN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  XXX_____,
  X_X_____,
  X_X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_043E[ 12] = { /* code 043E, CYRILLIC SMALL LETTER O */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _X______,
  X_X_____,
  X_X_____,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_043F[ 12] = { /* code 043F, CYRILLIC SMALL LETTER PE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  X_X_____,
  X_X_____,
  X_X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0440[ 12] = { /* code 0440, CYRILLIC SMALL LETTER ER */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  X_X_____,
  X_X_____,
  XX______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0441[ 12] = { /* code 0441, CYRILLIC SMALL LETTER ES */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  _XX_____,
  X_______,
  X_______,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0442[ 12] = { /* code 0442, CYRILLIC SMALL LETTER TE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  _X______,
  _X______,
  _X______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0443[ 12] = { /* code 0443, CYRILLIC SMALL LETTER U */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  XX______,
  _X______,
  _X______,
  X_______,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0444[ 12] = { /* code 0444, CYRILLIC SMALL LETTER EF */
  ________,
  ________,
  ________,
  ________,
  ________,
  __X_____,
  _XXX____,
  X_X_X___,
  X_X_X___,
  _XXX____,
  __X_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0445[ 12] = { /* code 0445, CYRILLIC SMALL LETTER HA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  _X______,
  _X______,
  X_X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0446[ 12] = { /* code 0446, CYRILLIC SMALL LETTER TSE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  XX______,
  XXX_____,
  __X_____,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0447[ 12] = { /* code 0447, CYRILLIC SMALL LETTER CHE */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_____,
  X_X_____,
  XXX_____,
  __X_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0448[ 12] = { /* code 0448, CYRILLIC SMALL LETTER SHA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_0449[ 12] = { /* code 0449, CYRILLIC SMALL LETTER SHCHA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_X_X___,
  X_X_X___,
  X_X_X___,
  XXXXX___,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_044A[ 12] = { /* code 044A, CYRILLIC SMALL LETTER HARD SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  _X______,
  _XX_____,
  _XX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_044B[ 12] = { /* code 044B, CYRILLIC SMALL LETTER YERU */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_______,
  XX______,
  XX______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_044C[ 12] = { /* code 044C, CYRILLIC SMALL LETTER SOFT SIGN */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  X_______,
  X_______,
  XX______,
  XX______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_044D[ 12] = { /* code 044D, CYRILLIC SMALL LETTER E */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  _X______,
  XX______,
  XX______,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_044E[ 12] = { /* code 044E, CYRILLIC SMALL LETTER YU */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXX_____,
  XXX_____,
  XXX_____,
  XXX_____,
  ________,
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fonttahoma12_044F[ 12] = { /* code 044F, CYRILLIC SMALL LETTER YA */
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XX______,
  XX______,
  _X______,
  XX______,
  ________,
  ________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fonttahoma12_CharInfo[159] = {
   {   2,   2,  1, acGUI_Fonttahoma12_0020 } /* code 0020 */
  ,{   2,   2,  1, acGUI_Fonttahoma12_0021 } /* code 0021 */
  ,{   2,   2,  1, acGUI_Fonttahoma12_0022 } /* code 0022 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0023 } /* code 0023 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0024 } /* code 0024 */
  ,{   8,   8,  1, acGUI_Fonttahoma12_0025 } /* code 0025 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0026 } /* code 0026 */
  ,{   1,   1,  1, acGUI_Fonttahoma12_0027 } /* code 0027 */
  ,{   2,   2,  1, acGUI_Fonttahoma12_0028 } /* code 0028 */
  ,{   2,   2,  1, acGUI_Fonttahoma12_0029 } /* code 0029 */
  ,{   2,   2,  1, acGUI_Fonttahoma12_002A } /* code 002A */
  ,{   3,   3,  1, acGUI_Fonttahoma12_002B } /* code 002B */
  ,{   2,   2,  1, acGUI_Fonttahoma12_002C } /* code 002C */
  ,{   2,   2,  1, acGUI_Fonttahoma12_002D } /* code 002D */
  ,{   2,   2,  1, acGUI_Fonttahoma12_002E } /* code 002E */
  ,{   2,   2,  1, acGUI_Fonttahoma12_002F } /* code 002F */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0030 } /* code 0030 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0031 } /* code 0031 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0032 } /* code 0032 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0033 } /* code 0033 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0034 } /* code 0034 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0035 } /* code 0035 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0036 } /* code 0036 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0037 } /* code 0037 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0038 } /* code 0038 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0039 } /* code 0039 */
  ,{   2,   2,  1, acGUI_Fonttahoma12_003A } /* code 003A */
  ,{   2,   2,  1, acGUI_Fonttahoma12_003B } /* code 003B */
  ,{   3,   3,  1, acGUI_Fonttahoma12_003C } /* code 003C */
  ,{   3,   3,  1, acGUI_Fonttahoma12_003D } /* code 003D */
  ,{   3,   3,  1, acGUI_Fonttahoma12_003E } /* code 003E */
  ,{   3,   3,  1, acGUI_Fonttahoma12_003F } /* code 003F */
  ,{   6,   6,  1, acGUI_Fonttahoma12_0040 } /* code 0040 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0041 } /* code 0041 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0042 } /* code 0042 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0043 } /* code 0043 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0044 } /* code 0044 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0045 } /* code 0045 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0046 } /* code 0046 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0047 } /* code 0047 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0048 } /* code 0048 */
  ,{   2,   2,  1, acGUI_Fonttahoma12_0049 } /* code 0049 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_004A } /* code 004A */
  ,{   4,   4,  1, acGUI_Fonttahoma12_004B } /* code 004B */
  ,{   3,   3,  1, acGUI_Fonttahoma12_004C } /* code 004C */
  ,{   5,   5,  1, acGUI_Fonttahoma12_004D } /* code 004D */
  ,{   4,   4,  1, acGUI_Fonttahoma12_004E } /* code 004E */
  ,{   4,   4,  1, acGUI_Fonttahoma12_004F } /* code 004F */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0050 } /* code 0050 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0051 } /* code 0051 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0052 } /* code 0052 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0053 } /* code 0053 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0054 } /* code 0054 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0055 } /* code 0055 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0056 } /* code 0056 */
  ,{   5,   5,  1, acGUI_Fonttahoma12_0057 } /* code 0057 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0058 } /* code 0058 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0059 } /* code 0059 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_005A } /* code 005A */
  ,{   2,   2,  1, acGUI_Fonttahoma12_005B } /* code 005B */
  ,{   2,   2,  1, acGUI_Fonttahoma12_005C } /* code 005C */
  ,{   2,   2,  1, acGUI_Fonttahoma12_005D } /* code 005D */
  ,{   3,   3,  1, acGUI_Fonttahoma12_005E } /* code 005E */
  ,{   3,   3,  1, acGUI_Fonttahoma12_005F } /* code 005F */
  ,{   2,   2,  1, acGUI_Fonttahoma12_0060 } /* code 0060 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0061 } /* code 0061 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0062 } /* code 0062 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0063 } /* code 0063 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0064 } /* code 0064 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0065 } /* code 0065 */
  ,{   2,   2,  1, acGUI_Fonttahoma12_0066 } /* code 0066 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0067 } /* code 0067 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0068 } /* code 0068 */
  ,{   1,   1,  1, acGUI_Fonttahoma12_0069 } /* code 0069 */
  ,{   1,   1,  1, acGUI_Fonttahoma12_006A } /* code 006A */
  ,{   3,   3,  1, acGUI_Fonttahoma12_006B } /* code 006B */
  ,{   1,   1,  1, acGUI_Fonttahoma12_006C } /* code 006C */
  ,{   5,   5,  1, acGUI_Fonttahoma12_006D } /* code 006D */
  ,{   3,   3,  1, acGUI_Fonttahoma12_006E } /* code 006E */
  ,{   3,   3,  1, acGUI_Fonttahoma12_006F } /* code 006F */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0070 } /* code 0070 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0071 } /* code 0071 */
  ,{   2,   2,  1, acGUI_Fonttahoma12_0072 } /* code 0072 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0073 } /* code 0073 */
  ,{   2,   2,  1, acGUI_Fonttahoma12_0074 } /* code 0074 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0075 } /* code 0075 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0076 } /* code 0076 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0077 } /* code 0077 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0078 } /* code 0078 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0079 } /* code 0079 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_007A } /* code 007A */
  ,{   2,   2,  1, acGUI_Fonttahoma12_007B } /* code 007B */
  ,{   1,   1,  1, acGUI_Fonttahoma12_007C } /* code 007C */
  ,{   2,   2,  1, acGUI_Fonttahoma12_007D } /* code 007D */
  ,{   3,   3,  1, acGUI_Fonttahoma12_007E } /* code 007E */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0410 } /* code 0410 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0411 } /* code 0411 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0412 } /* code 0412 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0413 } /* code 0413 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0414 } /* code 0414 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0415 } /* code 0415 */
  ,{   5,   5,  1, acGUI_Fonttahoma12_0416 } /* code 0416 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0417 } /* code 0417 */
  ,{   5,   5,  1, acGUI_Fonttahoma12_0418 } /* code 0418 */
  ,{   5,   5,  1, acGUI_Fonttahoma12_0419 } /* code 0419 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_041A } /* code 041A */
  ,{   4,   4,  1, acGUI_Fonttahoma12_041B } /* code 041B */
  ,{   5,   5,  1, acGUI_Fonttahoma12_041C } /* code 041C */
  ,{   4,   4,  1, acGUI_Fonttahoma12_041D } /* code 041D */
  ,{   4,   4,  1, acGUI_Fonttahoma12_041E } /* code 041E */
  ,{   4,   4,  1, acGUI_Fonttahoma12_041F } /* code 041F */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0420 } /* code 0420 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0421 } /* code 0421 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0422 } /* code 0422 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0423 } /* code 0423 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0424 } /* code 0424 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0425 } /* code 0425 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0426 } /* code 0426 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0427 } /* code 0427 */
  ,{   6,   6,  1, acGUI_Fonttahoma12_0428 } /* code 0428 */
  ,{   6,   6,  1, acGUI_Fonttahoma12_0429 } /* code 0429 */
  ,{   5,   5,  1, acGUI_Fonttahoma12_042A } /* code 042A */
  ,{   5,   5,  1, acGUI_Fonttahoma12_042B } /* code 042B */
  ,{   4,   4,  1, acGUI_Fonttahoma12_042C } /* code 042C */
  ,{   4,   4,  1, acGUI_Fonttahoma12_042D } /* code 042D */
  ,{   6,   6,  1, acGUI_Fonttahoma12_042E } /* code 042E */
  ,{   4,   4,  1, acGUI_Fonttahoma12_042F } /* code 042F */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0430 } /* code 0430 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0431 } /* code 0431 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0432 } /* code 0432 */
  ,{   2,   2,  1, acGUI_Fonttahoma12_0433 } /* code 0433 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0434 } /* code 0434 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0435 } /* code 0435 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_0436 } /* code 0436 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0437 } /* code 0437 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0438 } /* code 0438 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0439 } /* code 0439 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_043A } /* code 043A */
  ,{   3,   3,  1, acGUI_Fonttahoma12_043B } /* code 043B */
  ,{   4,   4,  1, acGUI_Fonttahoma12_043C } /* code 043C */
  ,{   3,   3,  1, acGUI_Fonttahoma12_043D } /* code 043D */
  ,{   3,   3,  1, acGUI_Fonttahoma12_043E } /* code 043E */
  ,{   3,   3,  1, acGUI_Fonttahoma12_043F } /* code 043F */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0440 } /* code 0440 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0441 } /* code 0441 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0442 } /* code 0442 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0443 } /* code 0443 */
  ,{   5,   5,  1, acGUI_Fonttahoma12_0444 } /* code 0444 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0445 } /* code 0445 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0446 } /* code 0446 */
  ,{   3,   3,  1, acGUI_Fonttahoma12_0447 } /* code 0447 */
  ,{   5,   5,  1, acGUI_Fonttahoma12_0448 } /* code 0448 */
  ,{   5,   5,  1, acGUI_Fonttahoma12_0449 } /* code 0449 */
  ,{   4,   4,  1, acGUI_Fonttahoma12_044A } /* code 044A */
  ,{   4,   4,  1, acGUI_Fonttahoma12_044B } /* code 044B */
  ,{   3,   3,  1, acGUI_Fonttahoma12_044C } /* code 044C */
  ,{   3,   3,  1, acGUI_Fonttahoma12_044D } /* code 044D */
  ,{   4,   4,  1, acGUI_Fonttahoma12_044E } /* code 044E */
  ,{   3,   3,  1, acGUI_Fonttahoma12_044F } /* code 044F */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttahoma12_Prop2 = {
   0x0410 /* first character */
  ,0x044F /* last character  */
  ,&GUI_Fonttahoma12_CharInfo[ 95] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fonttahoma12_Prop1 = {
   0x0020 /* first character */
  ,0x007E /* last character  */
  ,&GUI_Fonttahoma12_CharInfo[  0] /* address of first character */
  ,&GUI_Fonttahoma12_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fonttahoma12 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,12 /* height of font  */
  ,12 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fonttahoma12_Prop1}
  ,10 /* Baseline */
  ,4 /* Height of lowercase characters */
  ,5 /* Height of capital characters */
};

